# MEDICOS
medicos_findAll:
  path: /medicos
  controller: App\Controller\MedicosController::findAll
  methods:
    - GET

medicos_findById:
  path: /medicos/{id}
  controller: App\Controller\MedicosController::findById
  methods:
    - GET

medicos_remove:
  path: /medicos/{id}
  controller: App\Controller\MedicosController::remove
  methods:
    - DELETE

medicos_create:
  path: /medicos
  controller: App\Controller\MedicosController::create
  methods:
    - POST

medicos_update:
  path: /medicos/{id}
  controller: App\Controller\MedicosController::update
  methods:
    - PUT

# ESPECIALIDADES

especialidades_findAll:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::findAll
  methods:
    - GET

especialidades_findById:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::findById
  methods:
    - GET

especialidades_remove:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::remove
  methods:
    - DELETE

especialidades_create:
  path: /especialidades
  controller: App\Controller\EspecialidadesController::create
  methods:
    - POST

especialidades_update:
  path: /especialidades/{id}
  controller: App\Controller\EspecialidadesController::update
  methods:
    - PUT

